test from other dockr

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -90,13 +90,16 @@ jobs:
             set -ex
             docker run -d -p 514:514/udp --name syslog-ng ${DOCKER_IMAGE}:${VERSION}
             IP_CONTAINER=$( docker inspect syslog-ng | jq -r '.[0].NetworkSettings.IPAddress' )
-            for i in {auth,authpriv,cron,daemon,kern,lpr,mail,mark,news,syslog,user,uucp,local0,local1,local2,local3,local4,local5,local6,local7}; do
-            for k in {debug,info,notice,warning,err,crit,alert,emerg}; do
-            logger -p $i.$k -n $IP_CONTAINER --id=31415 -t "TESTMSG" "Test daemon message, facility $i priority $k"
-            done
-            done
+            docker run --network container:syslog-ng --name log-test debian logger -p user.warn -n $IP_CONTAINER --id=31415 -t "TESTMSG" "Test daemon message, priority warn"
+            mkdir -p workspace/syslog
             docker cp syslog-ng:/var/log/syslog-ng workspace/syslog
             docker stop syslog-ng
+            docker rm syslog-ng log-test
+
+            if ! ( grep -q -r -i "Test daemon message, priority warn" ); then
+            echo "Syslog message not found, exiting"
+            exit 1
+            fi
       - store_artifacts:
           path: workspace
 
